name: CapeCraftProxy
main: net.capecraft.spigot.SpigotMain
version: 1.0
authors: [james090500, mov51]
api-version: 1.14
commands:
  lobby:
    alias: hub
    description: Teleports to lobby
  survival:
    description: Teleports to survival
  creative:
    description: Teleports to creative   