name: CapeCraftProxy
main: net.capecraft.spigot.SpigotMain
version: 1.0
depends: [LuckPerms, Essentials]
authors: [james090500, mov51]
api-version: 1.15
commands:
  lobby:
    alias: hub
    description: Teleports to lobby
  survival:
    description: Teleports to survival
  creative:
    description: Teleports to creative
  send:
    description: Teleports all players to server
  wild:
    alias: rtp
    description: Teleports player to a random location