name: CapeCraftProxy
main: net.capecraft.spigot.SpigotMain
version: "1.0"
depends: [LuckPerms, Essentials]
authors: [james090500, mov51]
api-version: "1.15"
commands:
  lobby:
    alias: hub
    description: Teleports to lobby
  survival:
    description: Teleports to survival
  creative:
    description: Teleports to creative
  send:
    description: Teleports all players to server
  wild:
    alias: rtp
    description: Teleports player to a random location
permissions:
  capecraft.admin:
    description: Allows for usage of admin commands
  capecraft.fulljoin:
    description: Grants users the CapeCraft Fastpass
  capecraft.playafk:
    description: Allows for the use of the ./afk command