name: CapeCraftProxy
main: net.capecraft.Main
version: 1.0
author: james090500
commands:
  capecraftproxy:
    description: CapeCraftProxy commands
  rules:
    description: Show the rules
  altrules:
    description: Show alt the rules
  afkrules:
    description: Show afk the rules
  cape:
    description: cape command
  lobby:
    alias: hub
    description: Teleports to lobby
  survival:
    description: Teleports to survival
  creative:
    description: Teleports to creative   